"use client";

import React from "react";
import { 
  Sparkles, 
  Compass, 
  Zap, 
  Dumbbell, 
  LayoutDashboard,
  Users,
  FileText,
  BookOpen,
  Building2,
  Layers,
  ArrowRight,
  TrendingUp,
  Award
} from "lucide-react";
import Link from "next/link";
import { motion } from "framer-motion";

export default function DashboardPage() {
  const resourceCategories = [
    {
      title: "Core Learning",
      description: "Structured paths to master Data Structures and Algorithms.",
      items: [
        {
          name: "AI Roadmap",
          description: "Your personalized learning path generated by AI.",
          href: "/roadmap",
          icon: <Compass className="text-blue-500" />,
          badge: "AI Powered",
          pro: false
        },
        {
          name: "DSA Sheets",
          description: "Top-tier curated problem sets for interview prep.",
          href: "/dsa-sheet",
          icon: <LayoutDashboard className="text-brand-500" />,
          badge: "75+ Problems",
          pro: false
        },
        {
          name: "Masterclasses",
          description: "Live sessions and recorded lectures from experts.",
          href: "/masterclasses",
          icon: <BookOpen className="text-purple-500" />,
          pro: true
        }
      ]
    },
    {
      title: "Practice & Mastery",
      description: "Deep dive into specific topics or target top companies.",
      items: [
        {
          name: "Topic-wise Practice",
          description: "Master individual topics like DP, Graphs, and Trees.",
          href: "/practice/topics",
          icon: <Layers className="text-emerald-500" />,
          pro: false
        },
        {
          name: "Company Collections",
          description: "Practice questions asked by Google, Meta, and others.",
          href: "/practice/companies",
          icon: <Building2 className="text-orange-500" />,
          pro: true
        },
        {
          name: "Problem Arena",
          description: "A vast collection of 2000+ coding challenges.",
          href: "/practice",
          icon: <Zap className="text-yellow-500" />,
          badge: "2k+",
          pro: false
        }
      ]
    },
    {
      title: "Career & Tools",
      description: "Tools to help you stand out and land your dream job.",
      items: [
        {
          name: "Resume Builder",
          description: "Professional resume templates for tech roles.",
          href: "/resume",
          icon: <FileText className="text-rose-500" />,
          pro: false
        },
        {
          name: "Personalized Support",
          description: "1-on-1 mentorship and deep-dive learning.",
          href: "/personalized",
          icon: <Sparkles className="text-blue-400" />,
          badge: "Premium",
          pro: true
        },
        {
          name: "Community",
          description: "Connect with thousands of fellow aspirants.",
          href: "/community",
          icon: <Users className="text-indigo-400" />,
          pro: false
        }
      ]
    }
  ];

  return (
    <div className="max-w-6xl mx-auto space-y-10 pb-20 pt-4">
      {/* High-Impact Spotlight Row */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-4 items-center px-2">
        <div className="md:col-span-8 space-y-1">
          <h1 className="text-2xl font-black text-gray-900 dark:text-white tracking-tight">
            Dashboard Hub <span className="text-gray-400 font-medium ml-2">— Select Your Focus</span>
          </h1>
          <p className="text-sm text-gray-500 font-medium tracking-wide flex items-center gap-2 uppercase">
             <Sparkles size={14} className="text-brand-500" />
             Weekly Progress: <span className="text-emerald-500">+18% Success Rate</span>
          </p>
        </div>
        <div className="md:col-span-4 flex items-center justify-end gap-3">
           <div className="flex flex-col items-end">
              <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest leading-none">Global Rank</span>
              <span className="text-lg font-black text-gray-900 dark:text-white leading-none mt-1">Top 8%</span>
           </div>
           <div className="h-10 w-px bg-gray-200 dark:bg-gray-800 mx-2" />
           <Link href="/progress" className="flex items-center gap-1 text-xs font-bold text-brand-500 hover:underline">
              Full Stats <ArrowRight size={14} />
           </Link>
        </div>
      </div>

      {/* Resource Sections */}
      <div className="space-y-16">
        {resourceCategories.map((category, sectionIdx) => (
          <motion.div 
            key={category.title}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: sectionIdx * 0.1 }}
            className="space-y-8"
          >
            <div className="px-2 border-l-4 border-brand-500 ml-1 pl-6">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white">{category.title}</h2>
              <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">{category.description}</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {category.items.map((item, idx) => (
                <Link 
                  key={item.name}
                  href={item.href}
                  className="group relative flex flex-col overflow-hidden rounded-3xl border border-gray-200 bg-white p-6 transition-all hover:border-brand-500/30 hover:shadow-2xl hover:shadow-brand-500/5 dark:border-gray-800 dark:bg-gray-900/50 h-full"
                >
                  <div className="flex items-start justify-between mb-6">
                    <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-gray-50 dark:bg-white/5 transition-colors group-hover:bg-brand-500/10 border border-gray-100 dark:border-white/5">
                      {item.icon}
                    </div>
                    <div className="flex gap-2">
                       {item.badge && (
                         <span className="rounded-full bg-blue-500/10 px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider text-blue-600 border border-blue-500/10">
                            {item.badge}
                         </span>
                       )}
                       {item.pro && (
                         <span className="rounded-full bg-brand-500 px-2.5 py-0.5 text-[9px] font-bold uppercase tracking-widest text-white shadow-lg shadow-brand-500/20">
                            Pro
                         </span>
                       )}
                    </div>
                  </div>

                  <div className="space-y-2 flex-grow">
                    <h3 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2 group-hover:text-brand-500 transition-colors">
                      {item.name}
                      <ArrowRight size={16} className="opacity-0 -translate-x-2 transition-all group-hover:opacity-100 group-hover:translate-x-0" />
                    </h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">
                      {item.description}
                    </p>
                  </div>

                  <div className="mt-8 flex items-center gap-2 text-xs font-bold text-brand-500 group-hover:underline underline-offset-4">
                     Visit Module
                  </div>
                </Link>
              ))}
            </div>
          </motion.div>
        ))}
      </div>

      {/* Global Highlights Banner */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-10">
         <div className="relative overflow-hidden group rounded-3xl bg-blue-600 p-8 text-white">
            <TrendingUp className="absolute top-1/2 right-4 -translate-y-1/2 w-48 h-48 opacity-[0.05] rotate-12" />
            <h4 className="text-xl font-bold mb-2">Track Your Progress</h4>
            <p className="text-blue-100 text-sm max-w-[240px] mb-6">See how your skills have evolved over the last 30 days.</p>
            <Link href="/progress" className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-2 text-sm font-bold backdrop-blur-sm transition-all hover:bg-white hover:text-blue-600">
               Go to Progress Insights
            </Link>
         </div>

         <div className="relative overflow-hidden group rounded-3xl bg-emerald-600 p-8 text-white">
            <Award className="absolute top-1/2 right-4 -translate-y-1/2 w-48 h-48 opacity-[0.05] -rotate-12" />
            <h4 className="text-xl font-bold mb-2">CrackDSA Pro</h4>
            <p className="text-emerald-100 text-sm max-w-[240px] mb-6">Unlock deep-dives, company sheets, and expert mentorship.</p>
            <Link href="/pro" className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-2 text-sm font-bold backdrop-blur-sm transition-all hover:bg-white hover:text-emerald-600">
               Unlock Premium
            </Link>
         </div>
      </div>
    </div>
  );
}
